export const METRIC_NAME_MAP = {
  new_reliability_rating: "Reliability rating",
  new_security_rating: "Security rating",
  new_maintainability_rating: "Maintainability rating",
  new_coverage: "Coverage",
  new_duplicated_lines_density: "Duplications",
  new_security_hotspots_reviewed: "Security hotspots",
  new_security_review_rating: "Security Review Rating",
  new_branch_coverage: "Condition coverage on new code",
  new_line_coverage: "Line coverage on new code",
  new_blocker_violations: "Blocker Issues",
  new_bugs: "Bugs",
  new_code_smells: "Code smells",
  new_conditions_to_cover: "New lines to cover",
  new_critical_violations: "Critical Issues",
  new_duplicated_blocks: "Duplicated Blocks",
  new_duplicated_lines: "Duplicated Lines (%)",
  new_info_violations: "Info Issues",
  new_lines: "Lines",
  new_lines_to_cover: "Lines to cover",
  new_major_violations: "Major Issues",
  new_minor_violations: "Minor Issues",
  new_reliability_remediation_effort: "Reliability Remediation Effort",
  new_security_remediation_effort: "Security Remediation Effort",
  new_sqale_debt_ratio: "Technical Debt Ratio",
  new_technical_debt: "Technical Debt on New Code",
  new_uncovered_conditions: "Uncovered Conditions",
  new_uncovered_lines: "Uncovered Lines",
  new_violations: "Issues",
  new_vulnerabilities: "Vulnerabilities",
};

export const GRADE_MAP = {
  "1": "A",
  "2": "B",
  "3": "C",
  "4": "D",
  "5": "E",
  "6": "F",
};
